package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from d:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u40/3098/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Saturday, March 7, 2015 1:53:26 PM PST
*/

public interface CodeSets
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CONV_FRAME.CodeSetContext</code> defined in 
     * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
     */
  public static final int value = (int)(1L);
}
